name: CI

on:
  pull_request:

jobs:
  lint-and-type-check:
    name: Python Lint & Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install project dependencies
        run: uv sync --locked --all-extras --dev

      - name: Check formatting with Ruff
        run: uv run ruff format --diff .

      - name: Lint with Ruff
        run: uv run ruff check --output-format=github .
